# Site settings
title: Scribes of the Cairo Geniza
email: judaicadh@gmail.com
description: Scribes of the Cairo Geniza is an international collaboration led by the Penn Libraries in partnership with universities, libraries, and scholars to sort and transcribe thousands of medieval fragments. 

baseurl: /cairogeniza  # the subpath of your site, e.g. /blog/
url: https://judaicadh.github.io


# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: journal

# Build settings
markdown: kramdown
highlighter: rouge
plugins_dir:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: North America/Philadelphia
social:
- title: twitter
  url: http://twitter.com/judaicadh
- title: github
  url: https://github.com/judaicadh
- title: instagram
  url: https://instagram.com/judaica_dh
- title: facebook
  url: https://facebook.com/judaicadh
